# .github/workflows/deploy.yml
name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish
        id: publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: entropia-board-game
          directory: ./
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Discord success
        if: success()
        run: ./notify_discord.sh success ${{ steps.publish.outputs.url }} ${{ github.event.head_commit.message }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Discord failure
        if: failure()
        run: ./notify_discord.sh failure ${{ steps.publish.outputs.url }} ${{ github.event.head_commit.message }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
